name: CI/CD - Terraform-Jenkins

on:
  push:
    branches:
      - main
    paths:
      - github-actions_terraform_jenkins

jobs:


  aws_credentials:
      name: AWS Connection
      runs-on: ubuntu-latest
      
      steps:
        - name: AWS User 
          run: | 
            echo 'aws-user: aws_sandbox_admin'
        - name: AWS Access Key ID 
          run: | 
            echo 'aws-access-key-id: ' ${{ secrets.AWS_ACCESS_KEY_ID }}
        - name: AWS Secret Access Key 
          run: | 
            echo 'aws-secret-access-key: ' ${{ secrets.AWS_SECRET_ACCESS_KEY }}



  terraform:
    name: Terraform Validation and Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout tf code in runner environment
      uses: actions/checkout@v3.5.2

    - name: Configure AWS Credentials Action For GitHub Actions
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Setup Terraform CLI
      uses: hashicorp/setup-terraform@v2.0.2

    - name: Terraform init and validate
      run: |
        echo `pwd`
        echo "** Running Terraform Init**"
        terraform init
        
        echo "** Running Terraform Validate**"
        terraform validate
      working-directory: 'github-actions_terraform_jenkins_docker'
    - name: Terraform plan and apply
      run: |
        echo `pwd`
        echo "tfpath ${{ github.event.inputs.tfpath }}"        
        echo "** Running Terraform Plan**"
        terraform plan
        
        echo "** Running Terraform Apply**"
        terraform apply -auto-approve
      working-directory: 'github-actions_terraform_jenkins_docker'

    - name: Terraform Destroy
      run: |
        echo "** Running Terraform Destroy**"
        terraform destroy -auto-approve
      working-directory: 'github-actions_terraform_jenkins_docker'
